apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.auditif.repository }}:{{ .Values.auditif.tag }}"
          imagePullPolicy: {{ .Values.auditif.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
  {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
  {{- end }}
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.service.imagespullsecret }}
